### PR TITLE
Load thumbnail feature

### PR DESCRIPTION
**Pull request by abe-101**

### CODE REVIEW

**Comment by matevskial** [comment]
Thank you for the contribution, looks good. I'll merge this.

**Comment by abe-101** [comment]
Thank you!

**Comment by abe-101** [comment]
Would you be interested in collaborating together to implement a feature that would use YouTube publish date for the podcast Publish date? See https://github.com/Schrodinger-Hat/youtube-to-anchorfm/issues/32

**Comment by matevskial** [comment]
Sure, though this period I am quite busy with work and my graduate thesis, but we can collaborate, you can send a PR here, or or give suggestions etc.

**Comment by abe-101** [comment]
I can create an anv flag and parse the youtube json for the publish date.

The part I can't figure out is how to get puppeteer to input the date.

**Comment by matevskial** [comment]
My educated guess would be to do this:

Pupeteer may have a method to specifically set a date on a date input field, so you just have to prepare the date parsed from youtube in a correct format.

I can investigate this further when I have time.

**Pull request merged**
